### ISSUE TITLE
Release checklist for v0.35.0

### ISSUE THREAD

**Issue by cfryanr** [vmware-tanzu/pinniped#2091]
# Release checklist

- [x] Ensure that Pinniped's dependencies have been upgraded, to the extent desired by the team (refer to the diff output from the latest run of the [all-golang-deps-updated](https://ci.pinniped.dev/teams/main/pipelines/security-scan/jobs/all-golang-deps-updated/) CI job)
  - [x] If you are updating golang in Pinniped, be sure to update golang in CI as well.  Do a search-and-replace to update the version number everywhere in the pinniped `ci` branch.
  - [x] If the Fosite library is being updated and the format of the content of the Supervisor's storage Secrets are changed, or if any change to our own code changes the format of the content of the Supervisor's session storage Secrets, then be sure to update the `accessTokenStorageVersion`, `authorizeCodeStorageVersion`, `oidcStorageVersion`, `pkceStorageVersion`, `refreshTokenStorageVersion`, variables in files such as `internal/fositestorage/accesstoken/accesstoken.go`.  Failing tests should signal the need to update these values.
  - [x] For go.mod direct dependencies that are v2 or above, such as `github.com/google/go-github/vXX`, check to see if there is a new major version available.
  - [x] Evaluate all `replace` directives in the `go.mod` file. Are they up to date versions? Can any `replace` directives be removed?
- [x] Ensure that Pinniped's codegen is up-to-date with the latest Kubernetes releases by making sure this [file](https://github.com/vmware-tanzu/pinniped/blob/main/hack/lib/kube-versions.txt) is updated compared to the latest releases listed [here for active branches](https://kubernetes.io/releases/) and [here for non-active branches](https://kubernetes.io/releases/patch-releases/#non-active-branch-history)
  - [x] Added it to this PR so avoid having multiple open PRs: https://github.com/vmware-tanzu/pinniped/pull/2090
- [x] Ensure that the `k8s-code-generator` CI job definitions are up-to-date with the latest Go, K8s, and `controller-gen` versions
- [x] All relevant feature and docs PRs are merged
  - [x] https://github.com/vmware-tanzu/pinniped/pull/2090
- [x] The [main pipeline](https://ci.pinniped.dev/teams/main/pipelines/main) is green, up to and including the `ready-to-release` job. Check that the expected git commit has passed the `ready-to-release` job.
- [x] ~~Optional: a blog post for the release is written and submitted as a PR but not merged yet~~
- [x] All merged user stories are accepted (manually tested)
- [x] Only after all stories are accepted, manually trigger the `release` job to create a draft GitHub release
- [x] Manually edit the draft release notes on the [GitHub release](https://github.com/vmware-tanzu/pinniped/releases) to describe the contents of the release, using the format which was automatically added to the draft release
- [x] Publish (i.e. make public) the draft release
- [x] After making the release public, the jobs in the [main pipeline](https://ci.pinniped.dev/teams/main/pipelines/main) beyond the release job should auto-trigger, so check to make sure that they passed
- [x] ~~Edit the blog post's date to make it match the actual release date, and merge the blog post PR to make it live on the website~~
- [x] Publicize the release via tweets, etc.
- [x] Close this issue

**Comment by cfryanr** [comment]
DRAFT release notes:
---

## Changes

This release fixes a bug where updating some spec fields of JWTAuthenticators did not take effect immediately. It also upgrades all project dependencies.

### Minor Changes

- Updates the Kubernetes libraries to v0.31.2, and updates all other project dependencies. (#2088, #2086, #2084, #2082, #2076, #2075, #2074, #2072)
- The configuration and code for Pinniped's CI system and jobs have been made public in the `ci` branch of this repo. (#2077)

### Bug Fixes

- Fixes a bug introduce in Pinniped v0.33.0 where changing the `spec.audience` and/or `spec.claims` fields of an existing JWTAuthenticator (without changing any other spec fields) did not take effect until the next time the Concierge pods are restarted, even though those spec changes should take effect immediately. (#2090)

### Diffs

A complete list of changes (113 commits, 421 changed files with 25,654 additions and 11,665 deletions) can be found [here](https://github.com/vmware-tanzu/pinniped/compare/v0.34.0...v0.35.0).

**Comment by cfryanr** [comment]
Pinniped v0.35.0 is released! This release includes a bug fix related to JWTAuthenticators and updates all project dependencies. See release notes for details.
https://github.com/vmware-tanzu/pinniped/releases/tag/v0.35.0
