### ISSUE TITLE
Release checklist for v0.36.0

### ISSUE THREAD

**Issue by cfryanr** [vmware-tanzu/pinniped#2148]
# Release checklist

- [x] Ensure that Pinniped's dependencies have been upgraded, to the extent desired by the team (refer to the diff output from the latest run of the [all-golang-deps-updated](https://ci.pinniped.dev/teams/main/pipelines/security-scan/jobs/all-golang-deps-updated/) CI job)
  - [x] If you are updating golang in Pinniped, be sure to update golang in CI as well.  Do a search-and-replace to update the version number everywhere in the pinniped `ci` branch.
  - [x] If the Fosite library is being updated and the format of the content of the Supervisor's storage Secrets are changed, or if any change to our own code changes the format of the content of the Supervisor's session storage Secrets, then be sure to update the `accessTokenStorageVersion`, `authorizeCodeStorageVersion`, `oidcStorageVersion`, `pkceStorageVersion`, `refreshTokenStorageVersion`, variables in files such as `internal/fositestorage/accesstoken/accesstoken.go`.  Failing tests should signal the need to update these values.
  - [x] For go.mod direct dependencies that are v2 or above, such as `github.com/google/go-github/vXX`, check to see if there is a new major version available.
     - [x] See https://github.com/vmware-tanzu/pinniped/pull/2149
  - [x] Evaluate all `replace` directives in the `go.mod` file. Are they up to date versions? Can any `replace` directives be removed?
- [x] Ensure that Pinniped's codegen is up-to-date with the latest Kubernetes releases by making sure this [file](https://github.com/vmware-tanzu/pinniped/blob/main/hack/lib/kube-versions.txt) is updated compared to the latest releases listed [here for active branches](https://kubernetes.io/releases/) and [here for non-active branches](https://kubernetes.io/releases/patch-releases/#non-active-branch-history)
     - [x] Also added to https://github.com/vmware-tanzu/pinniped/pull/2149
- [x] Ensure that the `k8s-code-generator` CI job definitions are up-to-date with the latest Go, K8s, and `controller-gen` versions
    - [x] See https://github.com/vmware-tanzu/pinniped/commit/9960c8035176ba1cb6a833c9dae6f867bdf13e60
- [x] All relevant feature and docs PRs are merged
    - [x] One more dependency bump: https://github.com/vmware-tanzu/pinniped/pull/2150
- [x] The [main pipeline](https://ci.pinniped.dev/teams/main/pipelines/main) is green, up to and including the `ready-to-release` job. Check that the expected git commit has passed the `ready-to-release` job.
- [x] All merged user stories are accepted (manually tested)
- [x] Only after all stories are accepted, manually trigger the `release` job to create a draft GitHub release
- [x] Manually edit the draft release notes on the [GitHub release](https://github.com/vmware-tanzu/pinniped/releases) to describe the contents of the release, using the format which was automatically added to the draft release
- [x] Publish (i.e. make public) the draft release
- [x] After making the release public, the jobs in the [main pipeline](https://ci.pinniped.dev/teams/main/pipelines/main) beyond the release job should auto-trigger, so check to make sure that they passed
- [x] Publicize the release via tweets, etc.
- [x] Close this issue

**Comment by cfryanr** [comment]
DRAFT release notes

------

## Changes

This release introduces new audit logging capabilities. It also includes other enhancements and upgrades all project dependencies.

### Major Changes

- Authentication-related events are now audit-logged into the Supervisor and Concierge pod logs, allowing an administrator to trace a user's authentication journey across multiple clusters. They are marked with the JSON key-value pair `"auditEvent":true`. For more information, see the [audit logging documentation](https://pinniped.dev/docs/reference/audit-logging/). (#2009)

### Minor Changes

- The Concierge's controller which creates the "cert agent" Deployment now pays attention to which nodes are marked as unschedulable. When there are multiple running controller-manager pods to choose from, the controller will prefer to co-locate the cert agent pod with one that is running on a node which allows scheduling pods (where `spec.unschedulable` is equal to false), if possible. This has the effect of moving the pod away from nodes that are cordoned or are being drained, when another node is available. (#2143)
- Updates the Kubernetes libraries to v0.31.3, Golang to v1.23.3, and updates all other project dependencies. (#2147, #2145, #2142, #2139, #2123, #2121, #2119, #2109, #2107, #2100)
- Some small refactors and test improvements. (#2101, #2095, #2094)

### Diffs

A complete list of changes (105 commits, 123 changed files with 7,714 additions and 1,198 deletions) can be found [here](https://github.com/vmware-tanzu/pinniped/compare/v0.35.0...v0.36.0).

## Acknowledgements

Thanks to @trouphaz for reporting the issue that led to the improvement made by #2009.

**Comment by cfryanr** [comment]
Released! https://github.com/vmware-tanzu/pinniped/releases/tag/v0.36.0
